// Label templates for Label Shokunin

import type { LabelTemplate, LabelSize } from '~/types/label';

export const LABEL_TEMPLATES: LabelTemplate[] = [
  {
    id: 'simple',
    name: 'Simple',
    nameJa: 'シンプル',
    description: 'Barcode + Product Name + Price',
    size: '40x28',
    width: 40,
    height: 28,
    elements: [
      {
        type: 'barcode',
        x: 2,
        y: 2,
        width: 36,
        height: 12,
      },
      {
        type: 'text',
        x: 2,
        y: 15,
        width: 36,
        height: 6,
        field: 'productName',
        fontSize: 8,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        type: 'price',
        x: 2,
        y: 22,
        width: 36,
        height: 5,
        field: 'price',
        fontSize: 10,
        fontWeight: 'bold',
        textAlign: 'center',
        format: '¥{price}',
      },
    ],
  },
  {
    id: 'detailed',
    name: 'Detailed',
    nameJa: '詳細',
    description: 'Barcode + Product Name + SKU + Price + Tax',
    size: '60x40',
    width: 60,
    height: 40,
    elements: [
      {
        type: 'barcode',
        x: 2,
        y: 2,
        width: 56,
        height: 14,
      },
      {
        type: 'text',
        x: 2,
        y: 17,
        width: 56,
        height: 6,
        field: 'productName',
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'left',
      },
      {
        type: 'text',
        x: 2,
        y: 24,
        width: 30,
        height: 5,
        field: 'sku',
        fontSize: 7,
        fontWeight: 'normal',
        textAlign: 'left',
      },
      {
        type: 'price',
        x: 2,
        y: 30,
        width: 56,
        height: 8,
        field: 'price',
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'right',
        format: '¥{price}（税込）',
      },
    ],
  },
  {
    id: 'food',
    name: 'Food',
    nameJa: '食品用',
    description: 'Barcode + Product Name + Expiry Date + Price',
    size: '60x40',
    width: 60,
    height: 40,
    elements: [
      {
        type: 'text',
        x: 2,
        y: 2,
        width: 56,
        height: 6,
        field: 'productName',
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'left',
      },
      {
        type: 'barcode',
        x: 2,
        y: 9,
        width: 40,
        height: 12,
      },
      {
        type: 'price',
        x: 42,
        y: 9,
        width: 16,
        height: 12,
        field: 'price',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'right',
        format: '¥{price}',
      },
      {
        type: 'text',
        x: 2,
        y: 23,
        width: 56,
        height: 5,
        field: 'expiryDate',
        fontSize: 8,
        fontWeight: 'normal',
        textAlign: 'left',
        format: '賞味期限：{value}',
      },
      {
        type: 'text',
        x: 2,
        y: 29,
        width: 56,
        height: 10,
        field: 'taxNote',
        fontSize: 7,
        fontWeight: 'normal',
        textAlign: 'left',
      },
    ],
  },
  {
    id: 'apparel',
    name: 'Apparel',
    nameJa: 'アパレル用',
    description: 'Barcode + Product Name + Size + Color + Price',
    size: '60x40',
    width: 60,
    height: 40,
    elements: [
      {
        type: 'barcode',
        x: 2,
        y: 2,
        width: 56,
        height: 12,
      },
      {
        type: 'text',
        x: 2,
        y: 15,
        width: 56,
        height: 6,
        field: 'productName',
        fontSize: 8,
        fontWeight: 'bold',
        textAlign: 'left',
      },
      {
        type: 'text',
        x: 2,
        y: 22,
        width: 25,
        height: 5,
        field: 'size',
        fontSize: 9,
        fontWeight: 'bold',
        textAlign: 'left',
        format: 'サイズ: {value}',
      },
      {
        type: 'text',
        x: 28,
        y: 22,
        width: 30,
        height: 5,
        field: 'color',
        fontSize: 9,
        fontWeight: 'normal',
        textAlign: 'left',
        format: 'カラー: {value}',
      },
      {
        type: 'price',
        x: 2,
        y: 28,
        width: 56,
        height: 10,
        field: 'price',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'right',
        format: '¥{price}',
      },
    ],
  },
  {
    id: 'shelf',
    name: 'Shelf Label',
    nameJa: '棚札用',
    description: 'Barcode + Product Name + Large Price',
    size: '100x50',
    width: 100,
    height: 50,
    elements: [
      {
        type: 'text',
        x: 2,
        y: 2,
        width: 96,
        height: 8,
        field: 'productName',
        fontSize: 10,
        fontWeight: 'bold',
        textAlign: 'left',
      },
      {
        type: 'barcode',
        x: 2,
        y: 12,
        width: 50,
        height: 15,
      },
      {
        type: 'price',
        x: 54,
        y: 10,
        width: 44,
        height: 20,
        field: 'price',
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'right',
        format: '¥{price}',
      },
      {
        type: 'text',
        x: 54,
        y: 32,
        width: 44,
        height: 8,
        field: 'taxNote',
        fontSize: 10,
        fontWeight: 'normal',
        textAlign: 'right',
      },
      {
        type: 'text',
        x: 2,
        y: 42,
        width: 50,
        height: 6,
        field: 'sku',
        fontSize: 8,
        fontWeight: 'normal',
        textAlign: 'left',
      },
    ],
  },
];

export const LABEL_SIZES: Record<LabelSize, { name: string; width: number; height: number }> = {
  '40x28': { name: '40mm × 28mm（標準）', width: 40, height: 28 },
  '60x40': { name: '60mm × 40mm（中）', width: 60, height: 40 },
  '80x50': { name: '80mm × 50mm（大）', width: 80, height: 50 },
  '100x50': { name: '100mm × 50mm（棚札）', width: 100, height: 50 },
  'a4-24': { name: 'A4シート（24面）', width: 70, height: 37 },
  'a4-65': { name: 'A4シート（65面）', width: 38.1, height: 21.2 },
  'custom': { name: 'カスタムサイズ', width: 40, height: 28 },
};

export function getTemplateById(id: string): LabelTemplate | undefined {
  return LABEL_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesForSize(size: LabelSize): LabelTemplate[] {
  return LABEL_TEMPLATES.filter((t) => t.size === size);
}

// Label Printer Presets for Japanese market
export interface LabelPrinterPreset {
  id: string;
  name: string;
  brand: 'brother' | 'zebra' | 'sato' | 'aone' | 'generic';
  model?: string;
  paperCode?: string;  // e.g., DK-1201 for Brother
  width: number;       // mm
  height: number;      // mm (0 for continuous roll)
  continuous: boolean; // true for roll paper
  labelsPerPage?: number;  // for A4 sheet labels
  marginTop?: number;
  marginLeft?: number;
  gapBetweenLabels?: number;
  description: string;
}

export const LABEL_PRINTER_PRESETS: LabelPrinterPreset[] = [
  // Brother QL Series (DK Labels)
  {
    id: 'brother-dk-1201',
    name: 'Brother DK-1201 宛名ラベル',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-1201',
    width: 29,
    height: 90,
    continuous: false,
    description: '29mm×90mm（400枚/巻）',
  },
  {
    id: 'brother-dk-1209',
    name: 'Brother DK-1209 宛名ラベル（小）',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-1209',
    width: 62,
    height: 29,
    continuous: false,
    description: '62mm×29mm（800枚/巻）',
  },
  {
    id: 'brother-dk-1220',
    name: 'Brother DK-1220 食品表示用',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-1220',
    width: 39,
    height: 48,
    continuous: false,
    description: '39mm×48mm（620枚/巻）',
  },
  {
    id: 'brother-dk-1226',
    name: 'Brother DK-1226 食品表示/検体ラベル',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-1226',
    width: 52,
    height: 29,
    continuous: false,
    description: '52mm×29mm（1000枚/巻）',
  },
  {
    id: 'brother-dk-2205',
    name: 'Brother DK-2205 長尺紙テープ（62mm幅）',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-2205',
    width: 62,
    height: 0,
    continuous: true,
    description: '62mm幅×30.48m（任意の長さにカット可能）',
  },
  {
    id: 'brother-dk-2210',
    name: 'Brother DK-2210 長尺紙テープ（29mm幅）',
    brand: 'brother',
    model: 'QL-800 / QL-820NWB',
    paperCode: 'DK-2210',
    width: 29,
    height: 0,
    continuous: true,
    description: '29mm幅×30.48m（任意の長さにカット可能）',
  },
  // Brother TD Series
  {
    id: 'brother-td-40x28',
    name: 'Brother TD 40mm×28mm',
    brand: 'brother',
    model: 'TD-4550DNWB',
    width: 40,
    height: 28,
    continuous: false,
    description: 'TD-4550DNWB用 標準サイズ',
  },
  {
    id: 'brother-td-60x40',
    name: 'Brother TD 60mm×40mm',
    brand: 'brother',
    model: 'TD-4550DNWB',
    width: 60,
    height: 40,
    continuous: false,
    description: 'TD-4550DNWB用 中サイズ',
  },
  // Zebra ZD Series
  {
    id: 'zebra-zd-50x25',
    name: 'Zebra ZD 50mm×25mm',
    brand: 'zebra',
    model: 'ZD421 / ZD621',
    width: 50,
    height: 25,
    continuous: false,
    description: '標準バーコードラベル',
  },
  {
    id: 'zebra-zd-100x50',
    name: 'Zebra ZD 100mm×50mm',
    brand: 'zebra',
    model: 'ZD421 / ZD621',
    width: 100,
    height: 50,
    continuous: false,
    description: '大型配送ラベル',
  },
  {
    id: 'zebra-zd-102x152',
    name: 'Zebra ZD 102mm×152mm（4x6インチ）',
    brand: 'zebra',
    model: 'ZD421 / ZD621',
    width: 102,
    height: 152,
    continuous: false,
    description: '配送ラベル（4x6インチ）',
  },
  // SATO CL Series
  {
    id: 'sato-cl-40x28',
    name: 'SATO CL 40mm×28mm',
    brand: 'sato',
    model: 'CL4NX-J Plus',
    width: 40,
    height: 28,
    continuous: false,
    description: '標準バーコードラベル',
  },
  {
    id: 'sato-cl-60x40',
    name: 'SATO CL 60mm×40mm',
    brand: 'sato',
    model: 'CL4NX-J Plus',
    width: 60,
    height: 40,
    continuous: false,
    description: '中サイズラベル',
  },
  {
    id: 'sato-cl-100x50',
    name: 'SATO CL 100mm×50mm',
    brand: 'sato',
    model: 'CL4NX-J Plus',
    width: 100,
    height: 50,
    continuous: false,
    description: '棚札・大型ラベル',
  },
  // A-one シートラベル（A4）
  {
    id: 'aone-31513',
    name: 'エーワン 31513（10面）',
    brand: 'aone',
    width: 86.4,
    height: 50.8,
    continuous: false,
    labelsPerPage: 10,
    marginTop: 13.5,
    marginLeft: 18.6,
    gapBetweenLabels: 0,
    description: 'A4シート 86.4mm×50.8mm（10面）',
  },
  {
    id: 'aone-24面',
    name: 'エーワン 24面',
    brand: 'aone',
    width: 66,
    height: 33.9,
    continuous: false,
    labelsPerPage: 24,
    marginTop: 8.8,
    marginLeft: 7,
    gapBetweenLabels: 0,
    description: 'A4シート 66mm×33.9mm（24面）',
  },
  {
    id: 'aone-65面',
    name: 'エーワン 65面',
    brand: 'aone',
    width: 38.1,
    height: 21.2,
    continuous: false,
    labelsPerPage: 65,
    marginTop: 11.1,
    marginLeft: 7.3,
    gapBetweenLabels: 0,
    description: 'A4シート 38.1mm×21.2mm（65面）',
  },
  // Generic sizes
  {
    id: 'generic-40x28',
    name: '汎用 40mm×28mm',
    brand: 'generic',
    width: 40,
    height: 28,
    continuous: false,
    description: '標準サイズ（多くのプリンターに対応）',
  },
  {
    id: 'generic-50x30',
    name: '汎用 50mm×30mm',
    brand: 'generic',
    width: 50,
    height: 30,
    continuous: false,
    description: '中サイズ',
  },
  {
    id: 'generic-60x40',
    name: '汎用 60mm×40mm',
    brand: 'generic',
    width: 60,
    height: 40,
    continuous: false,
    description: '大サイズ',
  },
];

export function getPresetsByBrand(brand: LabelPrinterPreset['brand']): LabelPrinterPreset[] {
  return LABEL_PRINTER_PRESETS.filter((p) => p.brand === brand);
}

export function getPresetById(id: string): LabelPrinterPreset | undefined {
  return LABEL_PRINTER_PRESETS.find((p) => p.id === id);
}
